"""Collect the measurement pipeline's headline numbers into one generated JSON (never hand-typed).

Usage:
  python analysis/measure/make_numbers.py --seiko analysis/measure/results/seiko_validation.json \
      --dev analysis/measure/results/auto_vs_manual_dev.json \
      [--heldout analysis/measure/results/auto_vs_manual_heldout.json] \
      [--synthetic analysis/measure/results/benchmark_synthetic_summary.json] \
      [--foreperiods data/derived/foreperiods.csv] --out analysis/measure/numbers.json

Every value is copied from a results artifact; keys say which artifact and whether it is real or SYNTHETIC.
"""
import argparse
import json
import os

import pandas as pd


def load(p):
    if p and os.path.exists(p):
        with open(p, encoding="utf-8") as f:
            return json.load(f)
    return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--seiko", required=True)
    ap.add_argument("--dev", required=True)
    ap.add_argument("--heldout", default=None)
    ap.add_argument("--synthetic", default=None)
    ap.add_argument("--foreperiods", default=None)
    ap.add_argument("--out", required=True)
    a = ap.parse_args()
    out = {"_note": "Generated by analysis/measure/make_numbers.py from results artifacts. 'real_' = real broadcast "
                    "audio; 'synthetic_' = SIMULATED clips (synthetic benchmark), never real-race estimates."}
    s = load(a.seiko)
    if s:
        mo, mv, mw = s["manual"]["onset_minus_ready"], s["manual"]["voicing_end_minus_ready"], s["manual"]["word_end_minus_ready"]
        out.update({
            "real_seiko_n": s["n_compared"],
            "real_seiko_n_annotated_valid": s["n_valid_starts_annotated"],
            "real_seiko_n_excluded": len(s["excluded"]),
            "real_seiko_onset_minus_ready_bias_s": mo["bias_s"], "real_seiko_onset_minus_ready_sd_s": mo["sd_s"],
            "real_seiko_onset_minus_ready_mae_s": mo["mae_s"], "real_seiko_onset_minus_ready_min_s": mo["min_s"],
            "real_seiko_onset_minus_ready_max_s": mo["max_s"], "real_seiko_onset_within_20ms": mo["within_20ms"],
            "real_seiko_onset_within_40ms": mo["within_40ms"],
            "real_seiko_voicingend_minus_ready_bias_s": mv["bias_s"], "real_seiko_voicingend_minus_ready_sd_s": mv["sd_s"],
            "real_seiko_voicingend_minus_ready_mae_s": mv["mae_s"], "real_seiko_voicingend_minus_ready_min_s": mv["min_s"],
            "real_seiko_voicingend_minus_ready_max_s": mv["max_s"], "real_seiko_voicingend_within_20ms": mv["within_20ms"],
            "real_seiko_voicingend_within_40ms": mv["within_40ms"],
            "real_seiko_wordend_minus_ready_bias_s": mw["bias_s"], "real_seiko_wordend_minus_ready_sd_s": mw["sd_s"],
            "real_seiko_onset_within_champ_sd_s": s["manual"]["onset_minus_ready_within_championship_sd_s"],
            "real_seiko_voicingend_within_champ_sd_s": s["manual"]["voicing_end_minus_ready_within_championship_sd_s"],
            "real_seiko_corr_ready_fp_onset_r": s["manual"]["corr_ready_vs_fp_onset"].get("r"),
            "real_seiko_corr_ready_fp_onset_r_ci95": s["manual"]["corr_ready_vs_fp_onset"].get("r_ci95"),
            "real_seiko_auto_onset_minus_ready_bias_s": s["automated"]["onset_minus_ready"]["bias_s"],
            "real_seiko_auto_onset_minus_ready_sd_s": s["automated"]["onset_minus_ready"]["sd_s"],
        })
        fd = s.get("final_dataset_valid")
        if fd:
            out.update({"real_seiko_final_n": fd["n"],
                        "real_seiko_final_onset_minus_ready_bias_s": fd["onset_minus_ready"]["bias_s"],
                        "real_seiko_final_onset_minus_ready_sd_s": fd["onset_minus_ready"]["sd_s"],
                        "real_seiko_final_onset_minus_ready_min_s": fd["onset_minus_ready"]["min_s"],
                        "real_seiko_final_onset_within_40ms": fd["onset_minus_ready"]["within_40ms"],
                        "real_seiko_final_corr_r": fd["corr_ready_vs_fp_onset"].get("r"),
                        "real_seiko_final_corr_r_ci95": fd["corr_ready_vs_fp_onset"].get("r_ci95"),
                        "real_seiko_final_ols_slope": fd["corr_ready_vs_fp_onset"].get("ols_ready_on_fp_slope"),
                        "real_seiko_final_within_champ_sd_s": fd["within_championship_sd_s"],
                        "real_seiko_final_within_champ_mad_s": fd["within_championship_mad_s"]})
            for comp, v in fd["onset_minus_ready_by_championship"].items():
                out[f"real_seiko_final_{comp}_n"] = v["n"]
                out[f"real_seiko_final_{comp}_bias_s"] = v["bias_s"]
                out[f"real_seiko_final_{comp}_sd_s"] = v["sd_s"]
        aa = s.get("automated_all_measured_valid")
        if aa:
            out.update({"real_seiko_autoall_n": aa["n"],
                        "real_seiko_autoall_onset_minus_ready_bias_s": aa["onset_minus_ready"]["bias_s"],
                        "real_seiko_autoall_onset_minus_ready_sd_s": aa["onset_minus_ready"]["sd_s"],
                        "real_seiko_autoall_corr_r": aa["corr_ready_vs_fp_onset"].get("r"),
                        "real_seiko_autoall_corr_r_ci95": aa["corr_ready_vs_fp_onset"].get("r_ci95"),
                        "real_seiko_autoqcok_n": aa["qc_ok_onset_minus_ready"]["n"],
                        "real_seiko_autoqcok_onset_minus_ready_bias_s": aa["qc_ok_onset_minus_ready"]["bias_s"],
                        "real_seiko_autoqcok_onset_minus_ready_sd_s": aa["qc_ok_onset_minus_ready"]["sd_s"],
                        "real_seiko_autoqcok_corr_r": aa["qc_ok_corr_ready_vs_fp_onset"].get("r"),
                        "real_seiko_autoqcok_corr_r_ci95": aa["qc_ok_corr_ready_vs_fp_onset"].get("r_ci95"),
                        "real_seiko_autoqcok_ols_slope": aa["qc_ok_corr_ready_vs_fp_onset"].get("ols_ready_on_fp_slope")})
        for comp, v in s["manual"]["onset_minus_ready_by_championship"].items():
            out[f"real_seiko_onset_minus_ready_{comp}_n"] = v["n"]
            out[f"real_seiko_onset_minus_ready_{comp}_bias_s"] = v["bias_s"]
            out[f"real_seiko_onset_minus_ready_{comp}_sd_s"] = v["sd_s"]
        for comp, v in s["manual"]["voicing_end_minus_ready_by_championship"].items():
            out[f"real_seiko_voicingend_minus_ready_{comp}_bias_s"] = v["bias_s"]
    for tag, p in (("dev", a.dev), ("heldout", a.heldout)):
        d = load(p)
        if d:
            out[f"real_auto_vs_manual_{tag}_n_clean"] = d["n_clean"]
            for k in ("gun_onset", "set_onset_clean", "fp_onset_clean", "set_offset_vs_voicing_end_clean"):
                for m in ("n", "bias_ms", "mae_ms", "within_20ms", "within_40ms", "max_abs_ms"):
                    out[f"real_auto_vs_manual_{tag}_{k}_{m}"] = d[k].get(m)
    syn = load(a.synthetic)
    if syn:
        for k, v in syn.get("headline", {}).items():
            out[f"synthetic_{k}"] = v
    if a.foreperiods and os.path.exists(a.foreperiods):
        fp = pd.read_csv(a.foreperiods)
        out["real_foreperiods_n_rows"] = int(len(fp))
        out["real_foreperiods_n_races"] = int(fp.race_id.nunique())
        out["real_foreperiods_n_qc_ok"] = int((fp.qc_flag == "ok").sum())
        out["real_foreperiods_n_with_value"] = int(fp.foreperiod_s.notna().sum())
        out["real_foreperiods_n_races_with_value"] = int(fp[fp.foreperiod_s.notna()].race_id.nunique())
        out["real_foreperiods_n_valid_with_value"] = int(((fp.attempt_status == "valid") & fp.foreperiod_s.notna()).sum())
        out["real_foreperiods_n_recalled_with_value"] = int(((fp.attempt_status == "recalled") & fp.foreperiod_s.notna()).sum())
        out["real_foreperiods_n_unidentifiable"] = int(fp.foreperiod_s.isna().sum())
        v = fp[fp.foreperiod_s.notna()]
        out["real_foreperiods_median_s"] = round(float(v.foreperiod_s.median()), 4)
        out["real_foreperiods_min_s"] = round(float(v.foreperiod_s.min()), 4)
        out["real_foreperiods_max_s"] = round(float(v.foreperiod_s.max()), 4)
        for comp, g in v.groupby(v.race_id.str.split("-").str[0]):
            out[f"real_foreperiods_{comp}_n"] = int(len(g))
            out[f"real_foreperiods_{comp}_median_s"] = round(float(g.foreperiod_s.median()), 4)
    with open(a.out, "w", encoding="utf-8") as f:
        json.dump(out, f, indent=1)
        f.write("\n")


if __name__ == "__main__":
    main()
