#!/usr/bin/env python3
"""Render README.md from README.template.md. Every measured number comes from analysis/numbers.json.

    python scripts/render_readme.py            # write README.md
    python scripts/render_readme.py --check    # fail if README.md is not what the template renders to

Placeholders and asserts use paper/render.py's syntax ({{key|transform|format}}, {{key@field}}, and
<!-- assert: [key] ... --> comments that must hold). Other comments are author notes and are stripped.

The template's prose is audited for typed numbers: after removing placeholders, comments, code and links, every
remaining token with a digit must match one of the named design constants, citation facts or identifiers below.
"""
from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "paper"))
import render as R  # noqa: E402  (paper/render.py: placeholder and assert engine)

ALLOWED = [
    (r"\b2026-\d\d-\d\d\b", "date"),
    (r"0\.100-0\.300 s", "valid-RT window (design, analysis/common.py)"),
    (r"RT 0\.000", "missing-value placeholder in the source file (data fact)"),
    (r"\bsha256\b", "hash function name"),
    (r"section \d\b", "section reference"),
    (r"Attribution 4\.0", "licence name"),
    (r"0\.100 s", "false-start threshold (World Athletics TR 16.6)"),
    (r"0\.090", "lower edge of the near-threshold window (design)"),
    (r"0\.094 s", "Fiore et al. 2025 proposed threshold (literature input)"),
    (r"0\.119 s", "Brosnan et al. 2017 proposed threshold (literature input)"),
    (r"r = 0\.16|\|r\| (?:=|≥) 0\.16", "Haugen et al. 2013 published correlation (literature input, design value)"),
    (r"0\.001 s", "photo-finish timing resolution (literature input)"),
    (r"1-in-1,000", "barrier tail probability (design)"),
    (r"95%|80%", "confidence level / power (design)"),
    (r"per 1,000|per 100 ms", "units (design)"),
    (r"10th|90th|25th|75th", "percentiles compared (design)"),
    (r"(?:60|100|110|200|400) m\b|4x100|4x400", "event distance"),
    (r"k = 1\.645", "guard-band coverage factor (design, analysis/prereg_guardband.md)"),
    (r"\b(?:19[89]\d|20[0-2]\d)[a-z]?\b", "year (citation, championship or rule era)"),
    (r"\b(?:WCH|OG|WIC)(?:19|20)\d\d\b", "championship code"),
    (r"\b[HSOPM]\d{1,2}(?:-S4|\(a\)|\(b\))?\b", "pre-registered hypothesis / policy / model label"),
    (r"\bSSAC ?27\b|\bSSAC 2027\b", "venue"),
    (r"Python 3\.13(?:\.11)?|Windows 11", "software environment"),
    (r"CC BY 4\.0|CC0", "licence name"),
    (r"Figure 1", "figure number"),
    (r"TR ?16\.\d", "World Athletics rule number"),
    (r"\b5a12182\b", "commit of the false-start classifier fix in the working repository"),
    (r"(?m)^\s*\d+\.\s", "list or section number"),
    (r"^#+ \d+\.", "section number"),
    (r"\bSeed \d+|seed \d+", "random seed (design)"),
]
CODE = re.compile(r"```.*?```|`[^`\n]*`", re.S)
LINK_TARGET = re.compile(r"\]\([^)]*\)")


def literal_audit(template: str) -> list[str]:
    prose = R.PH.sub(" ", R.COMMENT.sub(" ", template))
    prose = LINK_TARGET.sub("] ", CODE.sub(" ", prose))
    for rx, _ in ALLOWED:
        prose = re.sub(rx, " ", prose, flags=re.M)
    bad = []
    for m in re.finditer(r"\S*\d\S*", prose):
        ctx = " ".join(prose[max(0, m.start() - 40):m.end() + 30].split())
        bad.append(f"{m.group(0)!r} in ...{ctx}...")
    return bad


def build(template: str, numbers: dict, nsha: str) -> tuple[str, list[str]]:
    errors = []
    for m in R.ASSERT.finditer(template):
        try:
            if not R.eval_assert(numbers, m.group(1)):
                errors.append(f"assert FALSE: {m.group(1)}")
        except R.RenderError as e:
            errors.append(str(e))
    errors += [f"typed numeric literal (not a named constant): {b}" for b in literal_audit(template)]

    def sub(m):
        try:
            return R.render_placeholder(numbers, m.group(1))
        except R.RenderError as e:
            errors.append(f"{{{{{m.group(1)}}}}}: {e}")
            return "??"

    stripped = re.sub(r"(?ms)^[ \t]*<!--.*?-->[ \t]*\n", "", template)
    body = R.PH.sub(sub, R.COMMENT.sub("", stripped))
    body = re.sub(r"[ \t]+\n", "\n", body)
    body = re.sub(r"\n{3,}", "\n\n", body).strip() + "\n"
    head = (f"<!-- Generated by scripts/render_readme.py from README.template.md and analysis/numbers.json "
            f"(sha256 {nsha}); do not edit by hand. -->\n")
    return head + body, errors


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--template", default="README.template.md")
    ap.add_argument("--numbers", default="analysis/numbers.json")
    ap.add_argument("--out", default="README.md")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args(argv)
    npath = ROOT / a.numbers
    numbers, _ = R.load_numbers(npath)
    nsha = hashlib.sha256(npath.read_bytes()).hexdigest()[:12]
    text, errors = build((ROOT / a.template).read_text(encoding="utf-8"), numbers, nsha)
    if errors:
        print("README render FAILED:\n  " + "\n  ".join(errors))
        return 2
    out = ROOT / a.out
    if a.check:
        same = out.exists() and out.read_text(encoding="utf-8") == text
        print("README.md is current" if same else "README.md is STALE: rerun scripts/render_readme.py")
        return 0 if same else 1
    out.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {a.out} ({len(R.PH.findall((ROOT / a.template).read_text(encoding='utf-8')))} placeholders, "
          f"{len(R.ASSERT.findall((ROOT / a.template).read_text(encoding='utf-8')))} asserts)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
