"""Build lit/refs.bib from lit/tools/refs_sources.tsv (+ lit/tools/refs_manual.bib).

refs_sources.tsv columns (tab-separated; '#' lines are comments):
    key <TAB> doi <TAB> note <TAB> print_year_override (optional)
- For each DOI, BibTeX is fetched from https://doi.org/<doi> by content negotiation
  (Accept: application/x-bibtex), the key is replaced by `key`, JATS/HTML tags are stripped
  from fields, an optional print-year override is applied (Crossref often reports the
  online-first year), and `note` (the verification tag used in lit/*.md) is appended.
- Manual entries (no DOI) are copied verbatim from refs_manual.bib.
- Fetched entries are cached in lit/tools/cache/, so re-running is offline and reproducible.

Usage (from the repo root):
    .venv/Scripts/python.exe lit/tools/build_refs.py
"""
import pathlib
import re
import sys
import time
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parents[1]      # lit/
SRC = ROOT / "tools" / "refs_sources.tsv"
MANUAL = ROOT / "tools" / "refs_manual.bib"
CACHE = ROOT / "tools" / "cache"
OUT = ROOT / "refs.bib"
CACHE.mkdir(parents=True, exist_ok=True)


def fetch(doi: str) -> str:
    fn = CACHE / (re.sub(r"[^A-Za-z0-9._-]", "_", doi) + ".bib")
    if fn.exists():
        return fn.read_text(encoding="utf-8")
    req = urllib.request.Request(
        "https://doi.org/" + doi,
        headers={"Accept": "application/x-bibtex; charset=utf-8",
                 "User-Agent": "ssac-lit/1.0"})
    for attempt in range(5):
        try:
            with urllib.request.urlopen(req, timeout=40) as r:
                txt = r.read().decode("utf-8", errors="replace").strip()
            if txt.startswith("@"):
                fn.write_text(txt, encoding="utf-8")
                return txt
        except Exception:  # network resets, timeouts: retry with backoff
            pass
        time.sleep(2 * (attempt + 1))
    raise RuntimeError(f"failed to fetch {doi}")


def clean(bib: str, key: str, note: str, year: str) -> str:
    bib = re.sub(r"^@(\w+)\{[^,]*,", lambda m: "@" + m.group(1) + "{" + key + ",", bib, count=1)
    bib = re.sub(r"</?(scp|i|b|sub|sup|em)>", "", bib)       # strip JATS/HTML tags
    bib = re.sub(r"\s*\n\s*", " ", bib)                       # collapse stray newlines
    if year:
        bib = re.sub(r"year=\{?\d{4}\}?", "year={" + year + "}", bib, count=1)
    if note:
        bib = bib.rstrip().rstrip("}").rstrip().rstrip(",") + ", note={" + note + "} }"
    bib = re.sub(r",\s*(\w+)=", r",\n  \1=", bib)             # one field per line
    return bib


def main() -> None:
    rows = [line.rstrip("\n").split("\t")
            for line in SRC.read_text(encoding="utf-8").splitlines()
            if line.strip() and not line.startswith("#")]
    out, missing, seen = [], [], set()
    for row in rows:
        key, doi = row[0].strip(), row[1].strip()
        note = row[2].strip() if len(row) > 2 else ""
        year = row[3].strip() if len(row) > 3 else ""
        if key in seen:
            sys.exit(f"duplicate key {key}")
        seen.add(key)
        if doi in ("", "-"):
            continue
        try:
            out.append(clean(fetch(doi), key, note, year))
        except Exception as e:  # report, do not abort
            missing.append((key, doi, str(e)))
    manual = MANUAL.read_text(encoding="utf-8") if MANUAL.exists() else ""
    for k in re.findall(r"^@\w+\{([^,]+),", manual, flags=re.M):
        if k in seen:
            sys.exit(f"manual key duplicates a DOI key: {k}")
    header = ("% refs.bib -- GENERATED by lit/tools/build_refs.py from lit/tools/refs_sources.tsv\n"
              "% (DOI entries via doi.org content negotiation, cached in lit/tools/cache/) plus\n"
              "% lit/tools/refs_manual.bib. note={...} carries the verification tag used in lit/*.md.\n\n")
    OUT.write_text(header + "\n\n".join(out) + "\n\n" + manual, encoding="utf-8")
    print(f"wrote {OUT} with {len(out)} DOI entries + manual block; missing={len(missing)}")
    for m in missing:
        print("MISSING", *m)


if __name__ == "__main__":
    main()
