"""Diff two numbers.json files (e.g. before and after a data fix) into a Markdown report.

Reports every key whose value or 95% CI changed (old -> new), the abstract template's placeholders rendered with both
files (via paper/render.py's own functions, so the text shown is what the abstract would print), every template
assertion evaluated with both, and every pre-registered verdict with its criteria fields.

Usage: .venv\\Scripts\\python.exe analysis\\diff_numbers.py --old <old numbers.json> --old-label "<commit, label>"
           --new analysis/numbers.json --template paper/abstract.template.md --out notes/bugfix_rerun_diff.md
           [--title "..."] [--context "..."]
"""
from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VERDICT_KEYS = ["systematic.h1_verdict", "systematic.h2_verdict", "systematic.h3_verdict_sign",
                "systematic.h3_verdict_haugen", "systematic.h3_verdict_han", "systematic.h4_verdict",
                "systematic.h5_verdict_reproduced", "systematic.h5_verdict_venue", "systematic.o2_verdict",
                "trend.s4_verdict", "trend.s4_verdict_lr", "trend.s4_verdict_inversion", "trend.h6_verdict"]
SKIP_FIELDS = {"desc", "source"}


def sha12(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()[:12]


def fmt(x) -> str:
    if x is None:
        return "-"
    if isinstance(x, bool) or isinstance(x, str):
        return str(x)
    if isinstance(x, float):
        return f"{x:.6g}"
    if isinstance(x, (list, tuple)):
        return "[" + ", ".join(fmt(e) for e in x) + "]"
    return str(x)


def load_render():
    spec = importlib.util.spec_from_file_location("render_for_diff", ROOT / "paper" / "render.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def rendered(R, numbers: dict, expr: str) -> str:
    try:
        return R.render_placeholder(numbers, expr)
    except Exception as e:  # missing key or field: shown, not hidden
        return f"(unavailable: {type(e).__name__})"


def asserted(R, numbers: dict, expr: str) -> str:
    try:
        return "true" if R.eval_assert(numbers, expr) else "FALSE"
    except Exception as e:
        return f"(unavailable: {type(e).__name__})"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--old", required=True)
    ap.add_argument("--old-label", required=True)
    ap.add_argument("--new", required=True)
    ap.add_argument("--template", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--title", default="numbers.json before vs after")
    ap.add_argument("--context", default="")
    a = ap.parse_args()
    po, pn = Path(a.old), ROOT / a.new
    old = json.loads(po.read_text(encoding="utf-8"))["numbers"]
    new = json.loads(pn.read_text(encoding="utf-8"))["numbers"]
    R = load_render()
    tpl = (ROOT / a.template).read_text(encoding="utf-8")
    asserts = R.ASSERT.findall(tpl)
    body = R.COMMENT.sub("", tpl)
    placeholders = list(dict.fromkeys(R.PH.findall(body)))
    tkeys = sorted({e.split("|")[0].split("@")[0].strip() for e in placeholders}
                   | {t.split("@")[0] for x in asserts for t in R.TOKEN.findall(x)})

    def changed(k):
        o, n = old[k], new[k]
        if k in VERDICT_KEYS:
            return {f: v for f, v in o.items() if f not in SKIP_FIELDS} != {f: v for f, v in n.items() if f not in SKIP_FIELDS}
        return o.get("value") != n.get("value") or o.get("ci95") != n.get("ci95")

    common = [k for k in old if k in new]
    ch = [k for k in common if changed(k)]
    added = [k for k in new if k not in old]
    removed = [k for k in old if k not in new]
    L = [f"# {a.title}", "",
         "Generated by `analysis/diff_numbers.py`; do not edit by hand.", ""]
    if a.context:
        L += [a.context, ""]
    L += [f"- Old: `{a.old_label}` (sha256 {sha12(po)}, {len(old)} keys).",
          f"- New: `{a.new}` (sha256 {sha12(pn)}, {len(new)} keys).",
          f"- Keys in both: {len(common)}; value or CI changed: {len(ch)}; unchanged: {len(common) - len(ch)}; "
          f"added: {len(added)} ({', '.join(sorted({k.split('.')[0] for k in added})) or 'none'}); removed: {len(removed)}.", ""]
    # ---- verdicts -------------------------------------------------------------------------------------------
    vchg = [k for k in VERDICT_KEYS if k in old and k in new and old[k].get("value") != new[k].get("value")]
    L += ["## Pre-registered verdicts", "",
          f"**Verdicts whose value changed: {len(vchg)}**" + (f" ({', '.join(vchg)})." if vchg else ".") +
          " 'Criteria changed' means the numbers behind an unchanged verdict moved.", "",
          "| key | old | new | verdict changed | criteria changed |", "|---|---|---|---|---|"]
    for k in VERDICT_KEYS:
        if k not in old and k not in new:
            continue
        o, n = old.get(k, {}), new.get(k, {})
        crit = lambda e: "; ".join(f"{f}={fmt(v)}" for f, v in e.items() if f not in SKIP_FIELDS | {"value", "unit"}
                                   and not isinstance(v, (dict, list)))
        if k not in old:
            vflag = cflag = "new"
        else:
            vflag = "**YES**" if o.get("value") != n.get("value") else "no"
            cflag = "yes" if changed(k) and vflag == "no" else ("-" if vflag != "no" else "no")
        L.append(f"| `{k}` | {fmt(o.get('value'))} ({crit(o)}) | {fmt(n.get('value'))} ({crit(n)}) | {vflag} | {cflag} |")
    L += ["", "Key names that changed: " + (", ".join(f"`{k}`" for k in removed) + " (no longer present; see Removed keys)"
                                           if removed else "none") + "."]
    # ---- abstract template ----------------------------------------------------------------------------------
    L += ["", f"## Abstract template (`{a.template}`)", "", "### Placeholders as rendered", "",
          "| placeholder | old text | new text | changed |", "|---|---|---|---|"]
    for e in placeholders:
        so, sn = rendered(R, old, e), rendered(R, new, e)
        esc = e.replace("|", r"\|")
        L.append(f"| `{{{{{esc}}}}}` | {so} | {sn} | {'**YES**' if so != sn else 'no'} |")
    L += ["", "### Assertions", "", "| assertion | old | new |", "|---|---|---|"]
    for x in asserts:
        xe = " ".join(x.split()).replace("|", r"\|")
        L.append(f"| `{xe}` | {asserted(R, old, x)} | {asserted(R, new, x)} |")
    L += ["", "### Keys the template uses", "", "| key | old value [CI] | new value [CI] | changed |", "|---|---|---|---|"]
    for k in tkeys:
        o, n = old.get(k), new.get(k)
        cell = lambda e: "(absent)" if e is None else f"{fmt(e.get('value'))} {fmt(e.get('ci95')) if e.get('ci95') else ''}".strip()
        flag = "**YES**" if (o is not None and n is not None and changed(k)) else ("added" if o is None and n is not None else
                                                                                   ("absent" if n is None else "no"))
        L.append(f"| `{k}` | {cell(o)} | {cell(n)} | {flag} |")
    # ---- every changed key ------------------------------------------------------------------------------------
    L += ["", "## Every key whose value or CI changed", ""]
    for pre in sorted({k.split(".")[0] for k in ch}):
        ks = [k for k in ch if k.split(".")[0] == pre]
        L += [f"### {pre} ({len(ks)})", "", "| key | old value | new value | old CI | new CI |", "|---|---|---|---|---|"]
        for k in ks:
            o, n = old[k], new[k]
            mark = " (template)" if k in tkeys else (" (verdict)" if k in VERDICT_KEYS else "")
            L.append(f"| `{k}`{mark} | {fmt(o.get('value'))} | {fmt(n.get('value'))} | {fmt(o.get('ci95'))} | {fmt(n.get('ci95'))} |")
        L.append("")
    if removed:
        import re
        stem = lambda k: re.sub(r"[\d.]+$", "", k)
        L += ["## Removed keys", "", "A key whose name embeds an estimate (for example the observed ICC in `power.*`) "
              "is renamed when the estimate moves; its successor is shown where the stems match.", ""]
        for k in removed:
            succ = [a2 for a2 in added if stem(a2) == stem(k)]
            if succ:
                L.append(f"- `{k}` -> `{succ[0]}` (value {fmt(old[k].get('value'))} -> {fmt(new[succ[0]].get('value'))})")
            else:
                L.append(f"- `{k}` (value {fmt(old[k].get('value'))}; no successor)")
        L.append("")
    Path(a.out).parent.mkdir(parents=True, exist_ok=True)
    Path(a.out).write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {a.out}: {len(ch)} changed of {len(common)}; {len(added)} added; {len(removed)} removed")


if __name__ == "__main__":
    main()
