"""Collect every reportable quantity into analysis/numbers.json (the single source for prose).

Each entry: "<result>.<key>": {value, ci95, unit, desc, ..., source, command, data}
  source  = repo-relative result JSON that holds the number
  command = the producer command registered for that JSON in producers.json
  data    = data versions (file@sha256 prefix, rows) of the inputs that result read
Refuses MOCK results. Output is deterministic (input order, no timestamps).

Usage: .venv\\Scripts\\python.exe analysis\\make_numbers.py --producers producers.json
           --in analysis/outputs/descriptive.json analysis/outputs/power.json ... --out analysis/numbers.json
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from common import ROOT, rel, version_tag


def data_versions(inputs, root=ROOT, seen=None):
    """Version tags of a result's inputs; follows result JSON inputs down to the data files."""
    seen = set() if seen is None else seen
    tags = []
    for v in inputs:
        pth = v.get("path", "")
        if pth.endswith(".json") and (root / pth).exists() and pth not in seen:
            seen.add(pth)
            sub = json.loads((root / pth).read_text(encoding="utf-8"))
            tags += data_versions(sub.get("inputs", []), root, seen)
        elif not pth.endswith(".json"):
            tags.append(version_tag(v))
    out = []
    for t in tags:
        if t not in out:
            out.append(t)
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--in", dest="inputs", nargs="+", required=True)
    ap.add_argument("--producers", default="producers.json")
    ap.add_argument("--extra", nargs="*", default=[],
                    help="flat number files owned by other stages, as PATH:PREFIX (e.g. analysis/measure/numbers.json:measure)")
    ap.add_argument("--out", required=True)
    a = ap.parse_args()
    prod_path = ROOT / a.producers
    producers = json.loads(prod_path.read_text(encoding="utf-8")) if prod_path.exists() else {}
    numbers, sources = {}, {}
    for p in a.inputs:
        pth = ROOT / p if not Path(p).is_absolute() else Path(p)
        d = json.loads(pth.read_text(encoding="utf-8"))
        if d.get("mock"):
            raise SystemExit(f"refusing MOCK result {p}")
        src = rel(pth)
        cmd = producers.get(src)
        dv = data_versions(d.get("inputs", []))
        sources[src] = {"name": d["name"], "command": cmd, "data": dv, "seed": d.get("seed")}
        for k, v in d["numbers"].items():
            entry = dict(v) if isinstance(v, dict) else {"value": v}
            entry["source"] = src
            numbers[f"{d['name']}.{k}"] = entry
    # merge flat number files from other stages (key -> value), provenance = file hash + producer
    for spec in a.extra:
        path_s, prefix = spec.rsplit(":", 1)
        pth = ROOT / path_s
        flat = json.loads(pth.read_text(encoding="utf-8"))
        src = rel(pth)
        from common import file_version
        sources[src] = {"name": prefix, "command": producers.get(src), "data": [version_tag(file_version(pth))],
                        "seed": None, "external": True}
        for k, val in flat.items():
            if k.startswith("_"):
                continue
            numbers[f"{prefix}.{k}"] = {"value": val, "desc": f"{prefix} agent number '{k}' (merged verbatim)",
                                        "source": src}
    # every result must have read the same version of each shared data file
    seen, conflicts = {}, []
    for src, info in sources.items():
        for tag in info["data"]:
            fname = tag.split("@")[0]
            if fname in seen and seen[fname] != tag:
                conflicts.append(f"{fname}: {seen[fname]} vs {tag} ({src})")
            seen.setdefault(fname, tag)
    if conflicts:
        raise SystemExit("inconsistent data versions across results; rerun run_all.py:\n  " + "\n  ".join(conflicts))
    out = {"_about": "Generated by analysis/make_numbers.py from the result JSONs listed in _sources. "
                     "Do not edit by hand; every reported quantity must come from here.",
           "_sources": sources, "_data_versions": sorted(seen.values()), "numbers": numbers}
    Path(a.out).parent.mkdir(parents=True, exist_ok=True)
    Path(a.out).write_text(json.dumps(out, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {a.out}: {len(numbers)} numbers from {len(sources)} results")


if __name__ == "__main__":
    main()
